/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;

/**
 *
 * @author user
 */
public class panel5 extends javax.swing.JPanel {

    String soil;
    /**
     * Creates new form panel5
     */
    public panel5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("Soil");
        add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "acidic", "loose", "fertile", "rich", "well-drained" }));
        add(jComboBox1);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jButton2.setText("Why?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                jTextArea1.setText("If soil is acidic, flower name could be Camellia.\n" +
                        "If soil is loose, flower name could be Begonia.\n" +
                        "If soil is fertile, flower name could be Begonia.\n" +
                        "If soil is rich, flower name could be Begonia.\n" +
                        "If soil is well-drained, flower name could be Rose.\n");
            }
        });
        add(jButton2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Globals.SOIL= (String)jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        panel6 p6=new panel6();
                this.remove(this.jButton1);
                this.remove(this.jButton2);
                 this.remove(this.jComboBox1);
                  this.remove(this.jScrollPane1);
                   this.remove(this.jTextArea1);
                   this.remove(this.jLabel1);
                this.add(p6);
                this.revalidate();
                this.repaint();
                p6.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
