/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;

/**
 *
 * @author user
 */
public class panel6 extends javax.swing.JPanel {

    String size;
    /**
     * Creates new form panel6
     */
    public panel6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField(7);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("Size");
        add(jLabel1);

        //jTextField1.setText("jTextField1");
        add(jTextField1);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jButton2.setText("Why?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                jTextArea1.setText("f size is between 10 & 50, the flower is considered small,\n" +
                        "If size is between 50 & 150, the flower is considered medium,\n" +
                        "If size is larger than 150, the flower is considered tall.\n" +

                        "A small flower could be Lily, Begonia.\n" +
                        "A Medium flower could be Chrysanthemum.\n" +
                        "A tall flower could be Dahlia.");
            }
        });
        add(jButton2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Globals.SIZE= jTextField1.getText();
        panel7 p7=new panel7();
                this.remove(this.jButton1);
                this.remove(this.jButton2);
                 this.remove(this.jTextField1);
                  this.remove(this.jScrollPane1);
                   this.remove(this.jTextArea1);
                   this.remove(this.jLabel1);
                this.add(p7);
                this.revalidate();
                this.repaint();
                p7.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
