/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class panel8 extends javax.swing.JPanel {

    String answer;
    /**
     * Creates new form panel8
     */
    public panel8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ClipsEnvironment clipsEnvironment = new ClipsEnvironment() ;
        jButton1.setText("What's My Flower ?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
                clipsEnvironment.assertdata(Globals.COLOR,Globals.SEASON,Globals.LIFECYCLE,Globals.SOIL,Globals.SIZE,Globals.PERUME,Globals.ROOT);
                clipsEnvironment.run();
                jLabel1.setText(clipsEnvironment.getFlower());
                clipsEnvironment.reset();
            }
        });
        add(jButton1);

        jLabel1.setText("your flower is ");
        add(jLabel1);

        jButton2.setText("How?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
    }// </editor-fold>   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       //You can write the action performed on clicking "what's my flower" button here
       //You can use the string answer already defined above
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       //You can write the action performed on clicking "How" button here
       
    }  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
