/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author user
 */
public class panel8  extends javax.swing.JPanel {

    String answer;
    /**
     * Creates new form panel8
     */
    public panel8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ClipsEnvironment clipsEnvironment = new ClipsEnvironment() ;
        jButton1.setText("What's My Flower ?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
                clipsEnvironment.assertdata(Globals.COLOR,Globals.SEASON,Globals.LIFECYCLE,Globals.SOIL,Globals.SIZE,Globals.PERUME,Globals.ROOT);
                clipsEnvironment.run();
                answer =clipsEnvironment.getFlower();
                jLabel1.setText(answer);
                clipsEnvironment.reset();
            }
        });
        add(jButton1);

        jLabel1.setText("your flower is ");
        add(jLabel1);

        jButton2.setText("How?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
    }// </editor-fold>   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       //You can write the action performed on clicking "what's my flower" button here
       //You can use the string answer already defined above
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       //You can write the action performed on clicking "How" button here
        try {
            if (answer.equals("The Flower is Iris")) {
                jTextArea1.setText("Becasue if season is summer\n" +
                        "and the color is " + Globals.COLOR + "\n" +
                        "and the life type is perennial\n" +
                        "and root type is bulb\n" +
                        "then flower name is Iris");
            }
            if (answer.equals("The Flower is Anemone")) {
                jTextArea1.setText("Becasue if season is autumn\n" +
                        "and the color is " + Globals.COLOR + "\n" +
                        "then flower name is Anemone");
            }
            if (answer.equals("The Flower is Chrysanthemum")) {
                jTextArea1.setText("Becasue if season is autumn\n" +
                        "and height is medium +\n" +
                        "and the color is " + Globals.COLOR + "\n" +
                        "then flower name is Anemone");
            }
            if (answer.equals("The Flower is Freesia")) {
                jTextArea1.setText("Becasue if season is spring\n" +
                        "and root type is bulb\n" +
                        "and the color is " + Globals.COLOR + "\n" +
                        "and perfumed is true\n" +
                        "then flower name is Freesia");
            }
            if (answer.equals("The Flower is Dahlia")) {
                jTextArea1.setText("Becasue if season is summer\n" +
                        "and root type is bulb\n" +
                        "and the height is tall\n" +
                        "then flower name is Dahlia");
            }
            if (answer.equals("The Flower is Narcissus")) {
                jTextArea1.setText("Becasue if season is spring\n" +
                        "and root type is bulb\n" +
                        "and the color is " + Globals.COLOR + "\n" +
                        "then flower name is Narcissus");
            }
            if (answer.equals("The Flower is Camellia")) {
                jTextArea1.setText("Becasue if soil is acidic\n" +
                        "and root type is roots\n" +
                        "and the color is " + Globals.COLOR + "\n" +
                        "and life type is perennial\n" +
                        "then flower name is Camellia");
            }
            if (answer.equals("The Flower is lily")) {
                jTextArea1.setText("Becasue if season is spring\n" +
                        "and root type is bulb\n" +
                        "and perfumed is true\n" +
                        "and height is small\n" +
                        "and life type is perennial\n" +
                        "then flower name is lily");
            }
            if (answer.equals("The Flower is Begonia")) {
                jTextArea1.setText(
                        "and soil is " + Globals.SOIL + "\n" +
                                "and height is small\n" +
                                "and life type is annual\n" +
                                "then flower name is Begonia");
            }
            if (answer.equals("The Flower is Azalea")) {
                jTextArea1.setText("Becasue if season is winter\n" +
                        "and the color is " + Globals.COLOR + "\n" +
                        "then flower name is Azalea");
            }
            if (answer.equals("The Flower is Azalea")) {
                jTextArea1.setText("Becasue if season is winter\n" +
                        "and the color is " + Globals.COLOR + "\n" +
                        "then flower name is Azalea");
            }
            if (answer.equals("The Flower is Rose")) {
                jTextArea1.setText(
                        "and the color is " + Globals.COLOR + "\n" +
                                "and life type is perennial\n" +
                                "and root type is root\n" +
                                "then flower name is Rose");
            }
            if (answer.equals("The Flower is white-lily")) {
                jTextArea1.setText("Becasue if season is spring\n" +
                        "and root type is bulb\n" +
                        "and perfumed is true\n" +
                        "and height is small\n" +
                        "and life type is perennial\n" +
                        "then flower name is white-lily");
            }
        }
        catch (NullPointerException e)
        {

        }
        
       
    }  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
